kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: awsebs
provisioner: kubernetes.io/aws-ebs
volumeBindingMode: WaitForFirstConsumer
parameters:
  type: gp2
  zones: us-east-1a, us-east-1b
  fsType: ext4
