kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-aws
  annotations:
    volume.beta.kubernetes.io/storage-class: "awsebs"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 32Gi
